import testerImg from '../../public/assets/images/products/product_23.jpg';

export const products = [
  {
    id: 1,
    name: 'The Body Keeps the Score',
    cover: '',
    media_type: 'pdf',
  },
  {
    id: 2,
    name: 'Mans Search for Meaning',
    cover: testerImg,
    media_type: 'video',
  },
  {
    id: 3,
    name: 'The Gifts of Imperfection',
    cover: '',
    media_type: 'pdf',
  },
  {
    id: 4,
    name: 'Feeling Good: The New Mood Therapy',
    cover: '',
    media_type: 'video',
  },
  {
    id: 5,
    name: 'Motivational Interviewing: Helping People Change',
    cover: '',
    media_type: 'pdf',
  },
  {
    id: 6,
    name: 'Mindfulness-Based Cognitive Therapy for Depression',
    cover: '',
    media_type: 'video',
  },
  {
    id: 7,
    name: 'The Dialectical Behavior Therapy Skills Workbook',
    cover: '',
    media_type: 'pdf',
  },
  {
    id: 8,
    name: 'ACT Made Simple',
    cover: '',
    media_type: 'video',
  },
  {
    id: 9,
    name: 'The Mindful Way Workbook',
    cover: '',
    media_type: 'pdf',
  },
  {
    id: 10,
    name: 'Radical Acceptance',
    cover: '',
    media_type: 'video',
  },
  {
    id: 11,
    name: 'Trauma and Recovery',
    cover: '',
    media_type: 'pdf',
  },
  {
    id: 12,
    name: 'The Four Agreements',
    cover: '',
    media_type: 'video',
  },
  {
    id: 13,
    name: 'Nonviolent Communication: A Language of Life',
    cover: '',
    media_type: 'pdf',
  },
  {
    id: 14,
    name: 'Self-Compassion: The Proven Power of Being Kind to Yourself',
    cover: '',
    media_type: 'video',
  },
  {
    id: 15,
    name: 'The Happiness Trap',
    cover: '',
    media_type: 'pdf',
  },
  {
    id: 16,
    name: 'You Are Not Your Brain',
    cover: '',
    media_type: 'video',
  },
  {
    id: 17,
    name: 'When Things Fall Apart',
    cover: '',
    media_type: 'pdf',
  },
  {
    id: 18,
    name: 'Healing the Shame That Binds You',
    cover: '',
    media_type: 'video',
  },
  {
    id: 19,
    name: 'The Power of Now',
    cover: '',
    media_type: 'pdf',
  },
  {
    id: 20,
    name: 'Attached: The New Science of Adult Attachment and How It Can Help You Find - and Keep - Love',
    cover: '',
    media_type: 'video',
  },
  {
    id: 21,
    name: 'The Anxiety and Phobia Workbook',
    cover: '',
    media_type: 'pdf',
  },
  {
    id: 22,
    name: 'Waking the Tiger: Healing Trauma',
    cover: '',
    media_type: 'video',
  },
  {
    id: 23,
    name: 'Lost Connections',
    cover: '',
    media_type: 'pdf',
  },
  {
    id: 24,
    name: 'Permission to Feel',
    cover: '',
    media_type: 'video',
  },
];
